name: Remote Deployment to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest  # This is the GitHub-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands using ssh-action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERS }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Navigate to the project directory
            cd /home/${{ secrets.HOST_USERS }}/cicd_jenkins_gaction || git clone https://github.com/${{ github.repository }}.git
            
            # 2. Enter folder and pull latest code
            cd cicd_jenkins_gaction
            git pull origin main
            
            # 3. Deploy using Docker Compose
            docker compose up --build -d
            
            # 4. Cleanup old unused images to save VPS space
            docker image prune -f
